name: Test Build & Publish Docker Image

on:
  push:
    branches:
      - container-test-build-publish
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build - Build the base image
        uses: docker/build-push-action@v3
        with:
          context: test
          tags: eespino/incubator-cloudberry:cbdb-test-alpine
          platforms: linux/amd64
          push: true
